"""Procurement standard fields, analytics view categories, and per-view field requirements."""

STANDARD_FIELDS: list[dict] = [
    {"id": 1, "type": "Invoice Details", "name": "Invoice Number", "description": "Invoice number"},
    {"id": 2, "type": "Invoice Details", "name": "Invoice Line Number", "description": "Invoice Line Number"},
    {"id": 3, "type": "Invoice Details", "name": "Invoice Date", "description": "Date the invoice was created"},
    {"id": 4, "type": "Invoice Details", "name": "Goods Receipt Date", "description": "Date when goods are received"},
    {"id": 5, "type": "Invoice Details", "name": "Invoice Line Description", "description": "Description of transaction explaining product/service bought"},
    {"id": 6, "type": "Invoice Details", "name": "Invoice Line Number Quantity", "description": "Quantity purchased for invoice line number"},
    {"id": 7, "type": "Invoice Details", "name": "Invoice Line Number Quantity UOM", "description": "Unit of measure for invoice line number quantity"},
    {"id": 8, "type": "Invoice Details", "name": "Local Currency Code", "description": "Currency of Total Amount in Local Currency"},
    {"id": 9, "type": "Invoice Details", "name": "Total Amount paid in Local Currency", "description": "Amount of Invoice Line in local currency"},
    {"id": 10, "type": "Invoice Details", "name": "Total Amount paid in Reporting Currency", "description": "Amount of Invoice Line in reporting currency"},
    {"id": 11, "type": "Invoice Details", "name": "Price per UOM", "description": "Price associated with invoice line item quantity"},
    {"id": 12, "type": "Invoice Details", "name": "Contract indicator", "description": "ON/OFF Contract spend indicator"},
    {"id": 13, "type": "Invoice Details", "name": "Fiscal Year", "description": "Fiscal year when the invoice was created"},
    {"id": 14, "type": "Invoice Details", "name": "Payment date", "description": "Date when Payment is made"},
    {"id": 15, "type": "Invoice Details", "name": "Debit/ Credit Indicator", "description": "Debit/Credit Indicator of amount"},
    {"id": 16, "type": "Invoice Details", "name": "PO Indicator", "description": "ON PO or NON PO spend indicator"},
    {"id": 17, "type": "PO Details", "name": "Invoice PO Number", "description": "PO Number linking to invoice"},
    {"id": 18, "type": "PO Details", "name": "Invoice PO Line Number", "description": "PO line item number"},
    {"id": 19, "type": "PO Details", "name": "PO Document Date", "description": "Date PO created"},
    {"id": 20, "type": "PO Details", "name": "PO Line Item Description 1", "description": "Primary description available in PO"},
    {"id": 21, "type": "PO Details", "name": "PO Material Group Description", "description": "Material/commodity group description"},
    {"id": 22, "type": "PO Details", "name": "PO Material Number", "description": "Material or Item number"},
    {"id": 23, "type": "PO Details", "name": "PO Material Description", "description": "Material description"},
    {"id": 24, "type": "PO Details", "name": "PO Material Group Code", "description": "Material/commodity group code"},
    {"id": 25, "type": "PO Details", "name": "PO Line Item Quantity", "description": "PO quantity"},
    {"id": 26, "type": "PO Details", "name": "PO Line Item Quantity UOM", "description": "PO UOM"},
    {"id": 27, "type": "PO Details", "name": "PO Local Currency Code", "description": "PO local currency"},
    {"id": 28, "type": "PO Details", "name": "PO Line Item Unit Price", "description": "PO unit price"},
    {"id": 29, "type": "PO Details", "name": "PO Manufacturer part number", "description": "Manufacturer part number"},
    {"id": 30, "type": "PO Details", "name": "PO Manufacturer name", "description": "Manufacturer name"},
    {"id": 31, "type": "PO Details", "name": "PO Line Item Description 2", "description": "Secondary PO description"},
    {"id": 32, "type": "PO Details", "name": "PO Total Amount in Local Currency", "description": "PO amount in local currency"},
    {"id": 33, "type": "PO Details", "name": "PO Total Amount in reporting currency", "description": "PO amount in reporting currency"},
    {"id": 34, "type": "Vendor Details", "name": "Vendor Code", "description": "Supplier code"},
    {"id": 35, "type": "Vendor Details", "name": "Vendor Name", "description": "Supplier name"},
    {"id": 36, "type": "Vendor Details", "name": "Vendor Country", "description": "Supplier country"},
    {"id": 37, "type": "Vendor Details", "name": "Vendor State", "description": "Supplier state"},
    {"id": 38, "type": "Vendor Details", "name": "Vendor Preferred Status", "description": "Preferred supplier indicator"},
    {"id": 39, "type": "Vendor Details", "name": "Vendor Address", "description": "Supplier address"},
    {"id": 40, "type": "Vendor Details", "name": "Vendor City", "description": "Supplier city"},
    {"id": 41, "type": "Vendor Details", "name": "Vendor Zip/Postal Code", "description": "Supplier postal code"},
    {"id": 42, "type": "Vendor Details", "name": "Vendor Diversity", "description": "Diversity indicator"},
    {"id": 43, "type": "Buyer Details", "name": "Business Unit", "description": "Business unit name"},
    {"id": 44, "type": "Buyer Details", "name": "Company Code", "description": "Legal entity code"},
    {"id": 45, "type": "Buyer Details", "name": "Company Name", "description": "Legal entity name"},
    {"id": 46, "type": "Buyer Details", "name": "Company Country", "description": "Legal entity country"},
    {"id": 47, "type": "Buyer Details", "name": "Plant Name", "description": "Facility name"},
    {"id": 48, "type": "Buyer Details", "name": "Plant Code", "description": "Facility code"},
    {"id": 49, "type": "Buyer Details", "name": "Plant Country", "description": "Facility country"},
    {"id": 50, "type": "Buyer Details", "name": "Plant State", "description": "Facility state"},
    {"id": 51, "type": "Buyer Details", "name": "Plant City", "description": "Facility city"},
    {"id": 52, "type": "Buyer Details", "name": "Business Division", "description": "Business division"},
    {"id": 53, "type": "Contract Details", "name": "Contract ID", "description": "Contract number"},
    {"id": 54, "type": "Contract Details", "name": "Contract party", "description": "Contract party name"},
    {"id": 55, "type": "Contract Details", "name": "Contract End Date", "description": "Contract end date"},
    {"id": 56, "type": "Contract Details", "name": "Contract Start Date", "description": "Contract start date"},
    {"id": 57, "type": "Contract Details", "name": "Payment Terms", "description": "Payment terms details"},
    {"id": 58, "type": "Contract Details", "name": "Contract Status", "description": "Contract status"},
    {"id": 59, "type": "Contract Details", "name": "Contract Description", "description": "Contract description"},
    {"id": 60, "type": "Procurement Details", "name": "Spend Classification Level 1", "description": "Category level 1"},
    {"id": 61, "type": "Procurement Details", "name": "Spend Classification Level 2", "description": "Category level 2"},
    {"id": 62, "type": "Procurement Details", "name": "Spend Classification Level 3", "description": "Category level 3"},
    {"id": 63, "type": "Procurement Details", "name": "Spend Classification Level 4", "description": "Category level 4"},
    {"id": 64, "type": "Procurement Details", "name": "Procurement Contract Owner", "description": "Procurement contract owner"},
    {"id": 65, "type": "Accounting Data", "name": "Cost Center Code", "description": "Cost center code"},
    {"id": 66, "type": "Accounting Data", "name": "Cost Center Description", "description": "Cost center name"},
    {"id": 67, "type": "Accounting Data", "name": "GL Account", "description": "GL code"},
    {"id": 68, "type": "Accounting Data", "name": "GL Account Description", "description": "GL description"},
    {"id": 69, "type": "Accounting Data", "name": "GL Account Hierarchy Level 1", "description": "GL hierarchy L1"},
    {"id": 70, "type": "Accounting Data", "name": "GL Account Hierarchy Level 2", "description": "GL hierarchy L2"},
    {"id": 71, "type": "Others", "name": "Currency Conversion rate", "description": "Currency conversion rate"},
    {"id": 72, "type": "Others", "name": "Data Source System", "description": "ERP system name"},
    {"id": 73, "type": "Others", "name": "Transaction ID", "description": "Unique transaction identifier"},
]

VIEW_CATEGORIES: dict[str, list[str]] = {
    "Contract": ["Contract Status", "Dynamic Spend View"],
    "Spend": [
        "FY20 Spend Overview",
        "Spend Distribution Summary",
        "Spend Profile - Monthly",
        "Spend type analysis",
        "Size of prize",
    ],
    "Supplier": [
        "Low Cost Country (LCC) Sourcing",
        "Mega Supplier Sourcing",
        "Supplier rationalization",
        "Spend by supplier country",
        "Peer to peer/ Industry benchmarking analysis",
        "Dynamic Category Savings",
    ],
    "Price": [
        "Price Rationalization",
        "Savings Potential - Price rationalization",
        "Specification rationalization",
        "Material wise deep dive ",
    ],
    "Compliance": [
        "Maverick Spend",
        "Transaction Intensity",
        "Centralized buying across plants/BUs",
    ],
    "Finance": ["Payment terms rationalization", "Supplier spend distribution by payment terms"],
}

VIEW_REQUIREMENTS: dict[str, list[str]] = {
    "Contract Status": [
        "Contract End Date",
        "Contract ID",
        "Contract indicator",
        "Invoice Date",
        "Invoice Number",
        "Vendor Name",
        "Contract Status",
        "Total Amount paid in Reporting Currency",
    ],
    "Dynamic Spend View": [
        "Business Unit",
        "Contract End Date",
        "Contract indicator",
        "Contract Start Date",
        "Invoice Date",
        "Invoice Number",
        "Invoice PO Number",
        "Vendor Name",
        "Contract Status",
        "Total Amount paid in Reporting Currency",
    ],
    "FY20 Spend Overview": [
        "Business Unit",
        "Invoice Date",
        "Invoice Number",
        "Vendor Name",
        "Total Amount paid in Reporting Currency",
    ],
    "Low Cost Country (LCC) Sourcing": [
        "Invoice Date",
        "Invoice Number",
        "Vendor Country",
        "Total Amount paid in Reporting Currency",
    ],
    "Material wise deep dive ": [
        "Contract End Date",
        "Contract ID",
        "Invoice Date",
        "Invoice Number",
        "PO Material Description",
        "PO Material Number",
        "Vendor Name",
        "Total Amount paid in Reporting Currency",
    ],
    "Maverick Spend": [
        "Contract ID",
        "Contract indicator",
        "Invoice Date",
        "Invoice Number",
        "Vendor Name",
    ],
    "Mega Supplier Sourcing ": [
        "Invoice Date",
        "Vendor Name",
        "Total Amount paid in Reporting Currency",
    ],
    "Payment terms rationalization ": [
        "Invoice Date",
        "Invoice Number",
        "Payment Terms",
        "Vendor Name",
        "Total Amount paid in Reporting Currency",
    ],
    "Peer to peer/ Industry benchmarking analysis ": [
        "Invoice Date",
        "Total Amount paid in Reporting Currency",
    ],
    "Price Rationalization ": [
        "Business Unit",
        "Contract ID",
        "Contract indicator",
        "Invoice Date",
        "Invoice Line Number Quantity",
        "Invoice Number",
        "PO Material Description",
        "PO Material Number",
        "Price per UOM",
        "Vendor Name",
        "Total Amount paid in Reporting Currency",
    ],
    "Savings Potential - Price rationalization": [
        "Contract ID",
        "Contract indicator",
        "Invoice Date",
        "Invoice Line Number Quantity",
        "Invoice Number",
        "PO Material Description",
        "PO Material Number",
        "Price per UOM",
        "Total Amount paid in Local Currency",
        "Vendor Name",
        "Total Amount paid in Reporting Currency",
    ],
    "Size of prize": ["Invoice Date", "Total Amount paid in Reporting Currency"],
    "Specification rationalization ": [
        "Business Unit",
        "Contract indicator",
        "Invoice Date",
        "Invoice Line Number Quantity",
        "Invoice Number",
        "PO Material Description",
        "PO Material Number",
        "Vendor Name",
        "Total Amount paid in Reporting Currency",
    ],
    "Spend by supplier country": [
        "Invoice Date",
        "Invoice Number",
        "Vendor Country",
        "Total Amount paid in Reporting Currency",
    ],
    "Spend Distribution Summary": [
        "Business Unit",
        "Invoice Date",
        "Invoice Number",
        "Vendor Name",
        "Plant Country",
        "Total Amount paid in Reporting Currency",
    ],
    "Spend Profile - Monthly ": [
        "Business Unit",
        "Contract ID",
        "Contract indicator",
        "Invoice Date",
        "Invoice Number",
        "Vendor Name",
        "Total Amount paid in Reporting Currency",
    ],
    "Spend type analysis ": [
        "Business Unit",
        "Contract indicator",
        "Invoice Date",
        "Invoice Number",
        "Vendor Name",
        "Total Amount paid in Reporting Currency",
    ],
    "Supplier rationalization": [
        "Invoice Date",
        "Vendor Name",
        "Total Amount paid in Reporting Currency",
    ],
    "Supplier spend distribution by payment terms": [
        "Invoice Date",
        "Payment Terms",
        "Vendor Name",
        "Total Amount paid in Reporting Currency",
    ],
    "Transaction Intensity": [
        "Business Unit",
        "Contract indicator",
        "Invoice Date",
        "Invoice Number",
        "Vendor Name",
        "Total Amount paid in Reporting Currency",
    ],
    "Centralized buying across plants/BUs": [
        "Business Unit",
        "Invoice Date",
        "Invoice Number",
        "Vendor Name",
        "Total Amount paid in Reporting Currency",
    ],
    "Dynamic Category Savings": ["Invoice Date", "Total Amount paid in Reporting Currency"],
}
